// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpncxlxsggpsiswoownv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbmN4bHhzZ2dwc2lzd29vd252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTM0OTgsImV4cCI6MjA1ODMyOTQ5OH0.nsm4z-lK97p-IGfUytp6SISz5OuWF7rHnnlgiK0gL0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);